### ISSUE TITLE
Building spead2 package on focal fails

### ISSUE THREAD

**Issue by Athanaseus** [ska-sa/spead2#137]
Hi I'm trying to make a KERN package for spead2 on ubuntu 20.04, which we will support only `python3` version of `spead2`.

Just trying to compile following the instructions on readthedocs i get the following:

`./configure --enable-lto AR=gcc-ar RANLIB=gcc-ranlib` worked fine.

`make` gave the following output:
```Making all in include
make[1]: Entering directory '/home/athanaseus/KERN/7/spead2-debian3/spead2/include'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/athanaseus/KERN/7/spead2-debian3/spead2/include'
Making all in src
make[1]: Entering directory '/home/athanaseus/KERN/7/spead2-debian3/spead2/src'
g++  -DNDEBUG  -I.  -I../include -I../include  -std=c++11    -O3 -flto  -I/usr/include/libnl3    -MT spead2_recv.o -MD -MP -MF .deps/spead2_recv.Tpo -c -o spead2_recv.o spead2_recv.cpp
In file included from spead2_recv.cpp:34:
../include/spead2/recv_udp_ibv.h:30:10: fatal error: rdma/rdma_cma.h: No such file or directory
   30 | #include <rdma/rdma_cma.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [Makefile:898: spead2_recv.o] Error 1
make[1]: Leaving directory '/home/athanaseus/KERN/7/spead2-debian3/spead2/src'
make: *** [Makefile:441: all-recursive] Error 1
```

When using debian tools I get the following:
```
./configure: line 3678: syntax error near unexpected token `IBV,'
./configure: line 3678: `  PKG_CHECK_MODULES(IBV, libibverbs librdmacm, SPEAD2_USE_IBV=1,'
make[1]: *** [debian/rules:16: override_dh_auto_configure] Error 2
make[1]: Leaving directory '/build/spead2-3.2.1'
```

Thank you in advance

**Comment by bmerry** [comment]
> ../include/spead2/recv_udp_ibv.h:30:10: fatal error: rdma/rdma_cma.h: No such file or directory

That's in librdmacm-dev. I would strongly suggest making librdmacm-dev, libibverbs-dev and libpcap-dev build-time dependencies and libpcap0.8 a runtime dependency. It's not necessary for libibverbs1 or librdmacm1 to be runtime dependencies, as spead2 loads them dynamically if needed (they could be suggested dependencies).

It's odd that you're getting this error at all though, because the configure script should check for these packages before trying to use them. Can you mail me the output of configure as well as config.log?

> ./configure: line 3678: `  PKG_CHECK_MODULES(IBV, libibverbs librdmacm, SPEAD2_USE_IBV=1,'

Are the debian tools rebuilding the configure script? If so you'll need to ensure that you have the necessary macro definitions for autoconf. For pkgconfig I think that should be in the `pkg-config` deb, but on the other hand I would have assumed that would already be installed on any reasonable system.

**Comment by Athanaseus** [comment]
Thanks @bmerry, indeed I was missing `pkg-config`. I'm using a pristine environment to do the package, so it requires providing all the dependencies to successfully build a package.

I can now find the `spead2` binaries after installing but I was  wondering how do I also have access to the python modules?
If I try using `pybuild` I get the following:

```
x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -O2 -fdebug-prefix-map=/build/spead2-3.2.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Ibuild/temp.linux-x86_64-3.8/include -Iinclude -I/usr/include/python3.8 -I/usr/include/python3.8 -c src/py_common.cpp -o build/temp.linux-x86_64-3.8/src/py_common.o -std=c++11 -g0 -fvisibility=hidden -I/usr/include/libnl3 -I/usr/include/libnl3
x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -O2 -fdebug-prefix-map=/build/spead2-3.2.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Ibuild/temp.linux-x86_64-3.8/include -Iinclude -I/usr/include/python3.8 -I/usr/include/python3.8 -c src/py_send.cpp -o build/temp.linux-x86_64-3.8/src/py_send.o -std=c++11 -g0 -fvisibility=hidden -I/usr/include/libnl3 -I/usr/include/libnl3
src/py_send.cpp: In function 'pybind11::module spead2::send::register_module(pybind11::module&)':
src/py_send.cpp:919:28: error: 'kw_only' is not a member of 'py'
  919 |              "heap"_a, py::kw_only(), "cnt"_a = -1, "substream_index"_a = 0,
      |                            ^~~~~~~
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
E: pybuild pybuild:341: build: plugin distutils failed with: exit code=1: /usr/bin/python3 setup.py build 
dh_auto_build: error: pybuild --build --test-nose -i python{version} -p 3.8 returned exit code 13
```

**Comment by Athanaseus** [comment]
Above can also be reproduced by:
`./bootstrap.sh`
`python3 setup.py build`

**Comment by bmerry** [comment]
Firstly, you shouldn't need to use `./bootstrap.sh` if you're building from a released version as the package, as the configure script and related files should already be present in released tarballs (it's needed if you're building from git master, but I don't recommend that for KERN).

It seems like pybuild might not support PEP 517 (https://linux.debian.bugs.dist.narkive.com/aXHrtv5n/bug-959407-dh-python-pybuild-without-setup-py), in which case you'll need to figure out how to get the Debian build system to use pip for installation (or manually provide the build-time dependencies specified in pyproject.toml).

**Comment by bmerry** [comment]
Or if Debian policies disallow downloading from PyPI as part of the build process, you might need to package a more recent pybind11 for KERN for use at build time.

**Comment by Athanaseus** [comment]
Providing the `pybind11` deps does seem to work. 
I resorted to taking the route of packaging a more recent pybind11 for KERN. 
I was just concerned with the fact that it requires `cmake>=3.18` and the latest available on focal is `3.16.3`.

These gave me the following output, which is related to tests:
```
...
A numpy style array split across several packets. It also ... ok                                                                                                                                                   
A basic array with numpy encoding ... ok                                                                                                                                                                           
tests.test_passthrough.TestPassthroughUdp.test_round_robin ... ERROR                                                                                                                                               
tests.test_passthrough.TestPassthroughUdp.test_round_robin_mixed_sizes ... ok                                                                                                                                      
Byte string is converted to array of characters and back. ... ok          
...
A basic array with numpy encoding ... ok
tests.test_passthrough.TestPassthroughUdp6Multicast.test_round_robin ... ERROR
tests.test_passthrough.TestPassthroughUdp6Multicast.test_round_robin_mixed_sizes ... ok
Byte string is converted to array of characters and back. ... ok
 ...
======================================================================
ERROR: tests.test_passthrough.TestPassthroughInproc.test_round_robin
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)                            
TypeError: test_round_robin() missing 1 required positional argument: 'size'

======================================================================
ERROR: tests.test_passthrough.TestPassthroughUdp.test_round_robin
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)                            
TypeError: test_round_robin() missing 1 required positional argument: 'size'

======================================================================
...
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 381, in setUp
    try_run(self.inst, ('setup', 'setUp'))
  File "/usr/lib/python3/dist-packages/nose/util.py", line 471, in try_run
    return func()                                   
  File "/home/athanaseus/KERN/7/spead2-debian3/spead2/.pybuild/cpython3_3.8_spead2/build/tests/test_passthrough.py", line 502, in setup
    self._extra_context = spead2.IbvContext(self._interface_address())
  File "/home/athanaseus/KERN/7/spead2-debian3/spead2/.pybuild/cpython3_3.8_spead2/build/tests/test_passthrough.py", line 493, in _interface_address
    pytest.skip('Envar SPEAD2_TEST_IBV_INTERFACE_ADDRESS not set')
  File "/usr/lib/python3/dist-packages/_pytest/outcomes.py", line 104, in skip
    raise Skipped(msg=msg, allow_module_level=allow_module_level)
Skipped: Envar SPEAD2_TEST_IBV_INTERFACE_ADDRESS not set
...
======================================================================
ERROR: tests.test_passthrough_asyncio.TestPassthroughUdpCustomSocket.test_round_robin
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)                            
TypeError: test_round_robin() missing 1 required positional argument: 'size'

======================================================================
ERROR: Packets without heap length rejected if disallowed
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)                            
TypeError: test_disallow_unsized_heaps() missing 1 required positional argument: 'caplog'

----------------------------------------------------------------------
Ran 344 tests in 1.747s                             

FAILED (errors=25)                                  
E: pybuild pybuild:341: test: plugin distutils failed with: exit code=1: cd /home/athanaseus/KERN/7/spead2-debian3/spead2/.pybuild/cpython3_3.8_spead2/build; python3.8 -m nose -v tests
dh_auto_test: error: pybuild --test --test-nose -i python{version} -p 3.8 returned exit code 13

```

**Comment by bmerry** [comment]
> I was just concerned with the fact that it requires cmake>=3.18 and the latest available on focal is 3.16.3.

I don't use the pybind11 cmake support, but potentially if someone installs the updated pybind11 and tries to use it with cmake one might run into issues.

> dh_auto_test: error: pybuild --test --test-nose -i python{version} -p 3.8 returned exit code 13

Use pytest, not nose.

**Comment by Athanaseus** [comment]
Thanks @bmerry, I have successfully built `spead2` and uploaded it to KERN.

**Comment by bmerry** [comment]
Excellent, thanks! I'll close this ticket then.
